export const AUTH_START = 'AUTH_START'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOGOUT = 'LOGOUT'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'

export const GET_AUTH_USER_DETAILS_SUCCESS = 'GET_AUTH_USER_DETAILS_SUCCESS'
export const GET_AUTH_USER_DETAILS_FAILURE = 'GET_AUTH_USER_DETAILS_FAILURE'
export const REMOVE_USER_DETAILS = 'REMOVE_USER_DETAILS'
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ'

export const LIKESCREAM = 'LIKESCREAM'
export const UNLIKESCREAM = 'UNLIKESCREAM'

export const CREATE_SCREAM = 'CREATE_SCREAM'
export const DELETE_SCREAM = 'DELETE_SCREAM'
export const GET_SCREAM_SUCCESS = 'GET_SCREAM_SUCCESS'
export const GET_SCREAM_START = 'GET_SCREAM_START'
export const GET_SCREAM_FAILURE = 'GET_SCREAM_FAILURE'

export const INCREMENT_LIKE = 'INCREMENT_LIKE'
export const DECREMENT_LIKE = 'DECREMENT_LIKE'










